import time

import keyboard as keyb


# import time

def commander():
    keyb.write('give_trait this GoodCommander 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodAttacker 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodDefender 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodAmbusher 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this Disciplinarian 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodSiegeAttacker 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodSiegeDefender 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this Brave 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this Energetic 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this PublicFaith 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodAdministrator 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this InspiringSpeaker 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this StrategicSkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this TacticalSkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this MathematicsSkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this LogisticalSkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Stoic 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Austere 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this SpyMaster 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this AssassinMaster 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this CounterSpy 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this AssassinCatcher 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this HighPersonalSecurity 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this Upright 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Authoritarian 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Loyal 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodFarmer 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodMiner 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodEngineer 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodTrader 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Just 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this KindRuler 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodBuilder 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Scout 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this BattleScarred 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this Fertile 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodTaxman 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Pragmatic 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this HaleAndHearty 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this TouchedByTheGods 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Intelligent 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Despoiler 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this NaturalMilitarySkill 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this CrusaderHistory 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this BattleChivalry 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this StrategyChivalry 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this CaptorChivalry 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this Gregarious 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this ContentGeneral 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this WifeIsWise 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this FathersLegacy 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this ChivalryLegacy 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this TourneyKnight 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this HorseRacer 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this ReligiousActivity 4\n')


def merchant():
    keyb.write('give_trait this GoodMerchant 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this NaturalMerchantSkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Monopolist 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this LegalDealer 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this SecureMerchant 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this SecurityMerchant 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this WorldlyMerchant 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this MerchantsGuildMember 1\n')
    time.sleep(0.1)
    keyb.write('give_trait this MerchantsGuildTrained 1\n')
    time.sleep(0.1)


def diplomat():
    keyb.write('give_trait this GoodDiplomat 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this SmoothTalker 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Secretive 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this NaturalDiplomatSkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Multilingual 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this ReligiousTolerance 3\n')
    time.sleep(0.1)


def spy():
    keyb.write('give_trait this GoodSpy 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodConspirator 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this NaturalSpySkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this ThievesGuildMember 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this ThievesGuildTrained 1\n')


def assassin():
    keyb.write('give_trait this GoodAssassin 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodConspirator 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this NaturalAssassinSkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this AssassinsGuildMember 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this HashashinsGuildMember 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this AssassinsGuildTrained 1\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodSaboteur 3\n')


def priest():
    keyb.write('give_trait this NaturalPriestSkill 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this PriestLevel 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodDenouncer 5\n')
    time.sleep(0.1)
    keyb.write('give_trait this Righteous 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this SecretlyFemale 1\n')
    time.sleep(0.1)
    keyb.write('give_trait this StrongFaith 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this DivineProtection 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this Purifier 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this Missionary 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this TheologiansGuildMember 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this TheologiansGuildTrained 1\n')


def princess():
    keyb.write('give_trait this HumbleWoman 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this PrettyWoman 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this BraveWoman 2\n')
    time.sleep(0.1)
    keyb.write('give_trait this FaithfulWoman 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this EducatedWoman 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this PassionateWoman 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this TolerantWoman 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this FertileWoman 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this FairWoman 3\n')
    time.sleep(0.1)
    keyb.write('give_trait this GoodPrincess 4\n')
    time.sleep(0.1)
    keyb.write('give_trait this NaturalPrincess 3\n')


keyb.add_hotkey('ctrl + 1', lambda: commander())
keyb.add_hotkey('ctrl + 2', lambda: merchant())
keyb.add_hotkey('ctrl + 3', lambda: diplomat())
keyb.add_hotkey('ctrl + 4', lambda: spy())
keyb.add_hotkey('ctrl + 5', lambda: assassin())
keyb.add_hotkey('ctrl + 6', lambda: priest())
keyb.add_hotkey('ctrl + 7', lambda: princess())

keyb.wait()
